name: Deploy to ECS Fargate

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 975050212504.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t pwoodproject .
          docker tag pwoodproject:latest 975050212504.dkr.ecr.us-east-2.amazonaws.com/containers/pwoodproject:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 975050212504.dkr.ecr.us-east-2.amazonaws.com/containers/pwoodproject:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ApacheCluster --service apache-service --force-new-deployment
